#:schema node_modules/wrangler/config-schema.json

workers_dev = true
name = "rr7-better-auth"
main = "./workers/server.ts"

# Compatibility
compatibility_date = "2024-11-18"
compatibility_flags = ["nodejs_compat"]

# Assets
assets = { directory = "./build/client/" }

# KV namespaces
kv_namespaces = [
  { binding = "AUTH_CACHE_KV", id = "auth_cache_kv_id" },
]

# Observability
[observability]
enabled = true

# Enable smart placement to optimize request latency and D1 database access
# https://developers.cloudflare.com/workers/configuration/smart-placement/
# [placement]
# mode = "smart"

# D1
[[d1_databases]]
binding = "DB"
database_name = "rr7-better-auth"
database_id = "database_id"
migrations_dir = "drizzle"

# Environment variables
[vars]
ENVIRONMENT = "development" # development | production

BETTER_AUTH_SECRET = "3ebc25b381e87193f29ffea6b6d380dd" # https://generate-secret.vercel.app/32
BETTER_AUTH_URL = "http://localhost:8787"

GITHUB_CLIENT_ID = "..."
GITHUB_CLIENT_SECRET = "..."

GOOGLE_CLIENT_ID = "..."
GOOGLE_CLIENT_SECRET = "..."
